Add a verifier that returns the full chains
github/ietf-cms pull request #4
Opened 2018-07-03 08:09 UTC by AntonioMA

This adds a couple of methods that instead of returning the leaf certificates, return the full chain used to verify each SignerInfo. I didn't change the signature of the existing methods so as to not break anything that might be using the current implementation.

Note that you could get the full chains from the leaf certificates by calling Verify again, but seemed like a waste of good computing power doing the work twice 😄

2018-07-03 16:50 UTC, btoews requested changes
This package is <1.0, so I don't mind making breaking changes. I agree that returning the full chains is useful, so let's just change the existing APIs to return this instead of adding new APIs.

2018-07-03 16:50 UTC, mastahyeti commented on verify.go
> +
There are a few whitespace issues in this diff. Please run `go fmt` to fix them.

2018-07-05 15:05 UTC, AntonioMA commented
I updated the PR as requested.

2018-07-05 16:24 UTC, mastahyeti commented
Thanks!

2018-07-05 16:24 UTC, merged